[project]
name = "proto-dw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.11.10",
    "dbt-postgres>=1.10.0",
    "dlt>=1.26.0",
    "duckdb>=1.5.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.13",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff]
extend-exclude = ["test_*.py"]
