dw_dbt:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: proto
      password: proto
      port: 5432
      dbname: proto_dw
      schema: public
      threads: 4
  target: dev
